services:
  - type: worker
    name: vbtool-telegram-bot
    runtime: python
    plan: 0.5c-512mb
    buildCommand: pip install -r requirements.txt
    startCommand: python botsever_v5.py.py
    numInstances: 1
    maxShutdownDelaySeconds: 30
    disk:
      name: vbtool-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: KEY_SERVER_ADMIN_SECRET
        sync: false
      - key: LINK4M_TOKEN
        sync: false
      - key: VUOTNHANH_TOKEN
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: KEY_SERVER_URL
        value: https://keyvip-sever1.onrender.com
      - key: VBTOOL_DATA_DIR
        value: /var/data
      - key: VBTOOL_BOT_SERVER_DEVICE_ID
        value: vbtool-render
      - key: ALLOWED_CHAT_IDS
        value: "801844480"
      - key: ADMIN_CHAT_IDS
        value: "8801844480"
